### ISSUE TITLE
article copyright 文末版权声明

### ISSUE THREAD

**Issue by MOxFIVE** [MOxFIVE/M-Hexo-Blog#13]
Need to show copyright statement at the end of an article automatically.
文末应该添加一些版权声明信息，样式应简洁，信息应便于复制。

**Comment by MOxFIVE** [comment]
Hide the copyright info via putting “original: false” to post’s [front-matter](https://hexo.io/docs/front-matter.html).
在 [front-matter](https://hexo.io/zh-cn/docs/front-matter.html) 中添加 “original: false” 可隐藏版权信息。

**Comment by MOxFIVE** [comment]
![cr](https://cloud.githubusercontent.com/assets/10032927/10000233/764dc1a6-60cd-11e5-93a3-bcc06e8f39ac.png)
http://moxfive.xyz/2015/08/20/blog-building/

**Comment by mingxianwei** [comment]
作者您好 ，我在添加这个版权声明后 这个原始链接不对  原文: http://yoursite.com/2015/12/17/写在开篇/　　作者: 小土豆  复制过来是这样的 这个 链接不对 怎么设置才能让它正常工作

**Comment by MOxFIVE** [comment]
需要在主配置中填好自己的主页  @mingxianwei
https://github.com/MOxFIVE/M-Hexo-Blog/blob/master/_config.yml#L15
https://hexo.io/zh-cn/docs/configuration.html#网址
